=== tpham20908/LabNAssgmt/Labs/BusinessLetter/BusinessLetter.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- The BusinessLetter element has Sender, Date, Receiver and LetterContent children elements -->
<!ELEMENT BusinessLetter (Sender, Date, Receiver, LetterContent)>

<!-- The Sender element has FirstName, LastName, Address children elements -->
<!ELEMENT Sender (FirstName, LastName, Address)>
<!-- Define elements in Sender element -->
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Address (AptNum?, StrNum, StrName, City, Province, CodePostal, Country?)>
<!-- Define elements in Address -->
<!ELEMENT AptNum (#PCDATA)>
<!ELEMENT StrNum (#PCDATA)>
<!ELEMENT StrName (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Province (#PCDATA)>
<!ELEMENT CodePostal (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!-- The Date element has Year, Month, Day children elements -->
<!ELEMENT Date (Year, Month, Day)>
<!-- Define elements in Date -->
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Month (#PCDATA)>
<!ELEMENT Day (#PCDATA)>
<!-- The Receiver element has Prefix, FirstName, LastName, Address children elements -->
<!ELEMENT Receiver (Prefix*, FirstName, LastName, Address)>
<!-- Define elements in Receiver -->
<!ELEMENT Prefix (#PCDATA)>
<!-- FirstName, LastName, Address have been defined above -->
<!-- The LetterContent has Greeting, MainContent, Ending children elements -->
<!ELEMENT LetterContent (Greeting, MainContent, Ending)>
<!-- Define elements in LetterContent -->
<!ELEMENT Greeting (#PCDATA)>
<!ELEMENT MainContent (#PCDATA)>
<!ELEMENT Ending (#PCDATA)>

=== tpham20908/LabNAssgmt/Labs/BusinessLetter/BusinessLetter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BusinessLetter SYSTEM "BusinessLetter.dtd">
<BusinessLetter>
	<Sender>
		<FirstName>John</FirstName>
		<LastName>Smith</LastName>
		<Address>
			<AptNum>123</AptNum>
			<StrNum>29</StrNum>
			<StrName>Sainte Catherine</StrName>
			<City>Montreal</City>
			<Province>QC</Province>
			<CodePostal>H3S1K8</CodePostal>
			<Country>Canada</Country>
		</Address>
	</Sender>
	<Date>
		<Year>2017</Year>
		<Month>September</Month>
		<Day>20</Day>
	</Date>
	<Receiver>
		<FirstName>Alan</FirstName>
		<LastName>Gaudet</LastName>
		<Address>
			<AptNum>BH116</AptNum>
			<StrNum>21275</StrNum>
			<StrName>LakeShore</StrName>
			<City>Sainte Anne De Bellevue</City>
			<Province>QC</Province>
			<CodePostal>H4T2G6</CodePostal>
			<Country>Canada</Country>
		</Address>
	</Receiver>
	<LetterContent>
		<Greeting>Dear Sir</Greeting>
		<MainContent>lkasd lasdjf asfkljs </MainContent>
		<Ending>Looking forward to see you soon.</Ending>
	</LetterContent>
</BusinessLetter>
