=== tpham20908/LabNAssgmt/Labs/CompanyTP/companyTP2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!ELEMENT ENTER_NAME_OF_ROOT_ELEMENT_HERE EMPTY> -->
<!-- DTD document for XML_CompanyTP -->
<!-- Developed by: Tung Pham -->
<!-- Script Date: September 20, 2017 -->
<!-- The CompanyTP element has a Name and multiple Departments -->
<!ELEMENT CompanyTP (CurrentDate, Name, Department+)>

<!-- Define CurrentDate -->
<!ELEMENT CurrentDate (#PCDATA)>
<!-- Declare the Today entity -->
<!-- Syntax: <!ENTITY entity_name "entity_value" > -->
<!-- <!ENTITY Today "September, 21 2017" > -->

<!-- Define the Name element -->
<!ELEMENT Name (#PCDATA)>
<!-- The Department element has one Name and zero or many Employee(s) -->
<!ELEMENT Department (Name, Employee*)>
<!-- The Employee element has EmployeeID, FirstName, LastName and Status (FullTime or PartTime)elements -->
<!ELEMENT Employee (EmployeeID, FirstName, LastName, (PartTime | FullTime))>
<!-- Define Employee children elements -->
<!ELEMENT EmployeeID (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>

<!-- The PartTime ele is an empty ele with an attribute named HourlyRate equals to $50.00 -->
<!ELEMENT PartTime EMPTY>
<!ATTLIST PartTime HourlyRate CDATA "$50.00">

<!-- FullTime ele has single child ele named StockOptionsGrant that may display zero or many times -->
<!ELEMENT FullTime (StockOptionsGrant*)>

<!-- FullTime ele has 2 attributes: Salary and Benefit package. The benefit package can be BPkg1, BPkg2 -->
<!ATTLIST FullTime 
	Salary CDATA #REQUIRED
	Benefit (BPkg1 | BPkg2 | BPkg3) "BPkg1">

<!-- The StockOptionsGrant ele is an empty ele with 2 atributes: TotalOptions and StrikePrice -->
<!ELEMENT StockOptionsGrant EMPTY>
<!ATTLIST StockOptionsGrant
	TotalOptions CDATA #REQUIRED
	StrikePrice CDATA #REQUIRED>

=== tpham20908/LabNAssgmt/Labs/CompanyTP/companyTP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CompanyTP SYSTEM "companyTP2.dtd">
<CompanyTP>
	<CurrentDate>&Today;</CurrentDate>
	<Name>
	</Name>
	<Department>
		<Name>IT Dept.</Name>
		<Employee>
			<EmployeeID>_101</EmployeeID>
			<FirstName>ADF</FirstName>
			<LastName>WEI</LastName>
			<PartTime HourlyRate="$50.00"/>
		</Employee>
		<Employee>
			<EmployeeID>_102</EmployeeID>
			<FirstName>GD</FirstName>
			<LastName>WE</LastName>
			<FullTime Salary="$75.00" Benefit="BPkg2">
				<StockOptionsGrant StrikePrice="$2.5" TotalOptions="$1200"/>
			</FullTime>
		</Employee>
	</Department>
</CompanyTP>

=== tpham20908/LabNAssgmt/Labs/CompanyTP/tmp0002.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CompanyTP SYSTEM "companyTP2.dtd">
<CompanyTP>
	<CurrentDate>ECMA</CurrentDate>
	<Name>
	</Name>
	<Department>
		<Name>IT Dept.</Name>
		<Employee>
			<EmployeeID>_101</EmployeeID>
			<FirstName>ADF</FirstName>
			<LastName>WEI</LastName>
			<PartTime HourlyRate="$50.00"></PartTime>
		</Employee>
		<Employee>
			<EmployeeID>_102</EmployeeID>
			<FirstName>GD</FirstName>
			<LastName>WE</LastName>
			<FullTime Salary="$75.00" Benefit="BPkg2">
				<StockOptionsGrant StrikePrice="$2.5" TotalOptions="$1200"></StockOptionsGrant>
			</FullTime>
		</Employee>
	</Department>
</CompanyTP>
